### ISSUE TITLE
Allow zip compress level especially NO_COMPRESS

### ISSUE THREAD

**Issue by wesleywu** [brimworks/lua-zip#4]
Sometimes I need to add mp3/jpg files into a zip archive.
Maybe adding files as NO_COMPRESS will save some CPU time.

**Comment by MisterDA** [comment]
Hi ! It seems that this feature has been implemented now. See [zip_set_file_compression](http://www.nih.at/libzip/zip_set_file_compression.html). Can you add it too to your binding ?
Thanks a lot !
